/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import com.mysql.cj.xdevapi.Statement;
import javax.swing.JOptionPane;
import conexion.conectar;
import java.awt.Desktop;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.awt.event.KeyAdapter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 *
 * @author USUARIO
 */
public class VistaPensiones_Balances extends javax.swing.JFrame {
Connection conexion = new conectar().conectar();
    
    public VistaPensiones_Balances() {
        initComponents();
        setLocationRelativeTo(null);
        Mostrar("");
       
        contarAlumnos();
       
        jbtnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPagosActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtAPaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtAMaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbxNivel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jcbxCuotaDelMes = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jtxtCorreo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtTotalPagar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtBalancedeTodo = new javax.swing.JTextField();
        jbtnPagos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbtnReportes = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTablaRegistroDePensiones = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtNumeroRegistros = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jbtnGuardar = new javax.swing.JButton();
        jbtnModificar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Estudiante ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14)))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Codigo del Estudiante:");

        jtxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodigoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Apellido Paterno:");

        jtxtAPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAPaternoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Apellido Materno:");

        jtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");

        jtxtAMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAMaternoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nivel o Salon:");

        jcbxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 añitos", "4 añitos", "5 añitos" }));
        jcbxNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxNivelActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Cuota del Mes:");

        jcbxCuotaDelMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jcbxCuotaDelMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxCuotaDelMesActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Numero Apoderado:");

        jtxtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCorreoActionPerformed(evt);
            }
        });

        jLabel21.setText("estudiante->codifgo bd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtAPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(jtxtAMaterno)
                            .addComponent(jtxtNombre)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21))
                            .addComponent(jtxtCorreo)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbxNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbxCuotaDelMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxCuotaDelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion de Tarifas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14)))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/programmer_3770431.png"))); // NOI18N

        jLabel6.setText("Monto:");

        jtxtTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalPagarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Balance Total Adeudados:");

        jtxtBalancedeTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBalancedeTodoMouseClicked(evt);
            }
        });
        jtxtBalancedeTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBalancedeTodoActionPerformed(evt);
            }
        });

        jbtnPagos.setText("Balance");
        jbtnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPagosActionPerformed(evt);
            }
        });

        jButton3.setText("GENERAR CONTROL DE REGISTRO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jbtnReportes.setText("GENERAR BALANCE");
        jbtnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReportesActionPerformed(evt);
            }
        });

        jLabel22.setText("Apoderado:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtTotalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addGap(109, 109, 109))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbtnPagos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtBalancedeTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBalancedeTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla Registro de Pensiones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jtblTablaRegistroDePensiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Apellido Paterno", "Apellido Materno", "Total Adeudado o Pago", "Nivel", "Mes", "Fecha", "Avance Tarifa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblTablaRegistroDePensiones.setFocusable(false);
        jtblTablaRegistroDePensiones= new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jtblTablaRegistroDePensiones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtblTablaRegistroDePensiones.getTableHeader().setResizingAllowed(false);
        jtblTablaRegistroDePensiones.getTableHeader().setReorderingAllowed(false);
        jtblTablaRegistroDePensiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblTablaRegistroDePensionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblTablaRegistroDePensiones);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Ingrese el ID del Estudiante a Buscar: ");

        jtxtNumeroRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumeroRegistrosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Numero de Registros:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtNumeroRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtNumeroRegistros))))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/newfile_85903_1.png"))); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/save_icon_125167.png"))); // NOI18N
        jbtnGuardar.setText("Guardar ");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        jbtnModificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1159633.png"))); // NOI18N
        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });

        jbtnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/3159218.png"))); // NOI18N
        jbtnEliminar.setText("Eliminar ");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        jbtnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/402720.png"))); // NOI18N
        jbtnSalir.setText("Salida");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jbtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnModificar)
                .addGap(18, 18, 18)
                .addComponent(jbtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnEliminar)
                    .addComponent(jbtnSalir))
                .addContainerGap())
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/kindpng_266572.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sistema de Registro de pago");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pensión- Balance");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel15))))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodigoActionPerformed

    private void jtxtAPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAPaternoActionPerformed

    private void jtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreActionPerformed

    private void jtxtAMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAMaternoActionPerformed

    private void jcbxNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxNivelActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
    jTextField5.addKeyListener(new KeyAdapter() {
    public void keyReleased(KeyEvent evt) {
        String estudiante = jTextField5.getText();
        Mostrar(estudiante);
    }
});

    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jtxtCodigo.setText("");
        jtxtAPaterno.setText("");
        jtxtNombre.setText("");
        jtxtAMaterno.setText("");
        jtxtTotalPagar.setText("");
        jtxtCorreo.setText("");
        jTextField1.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        Guardar();
        Mostrar("");
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
int selectedRow = jtblTablaRegistroDePensiones.getSelectedRow();
    if (selectedRow != -1) {
        String codigoEstudiante = jtblTablaRegistroDePensiones.getValueAt(selectedRow, 0).toString();
        try {
            String sql = "UPDATE apellidopaterno SET " +
                         "nombres = ?, " +
                         "apellido = ?, " +
                         "materno = ?, " +
                         "pago = ?, " +
                         "nivel = ?, " +
                         "mes = ?, " +
                         "numero = ?, " +  
                         "apoderado = ? " + 
                         "WHERE estudiante = ?";

            PreparedStatement pasar = conexion.prepareStatement(sql);
            pasar.setString(1, jtxtNombre.getText());
            pasar.setString(2, jtxtAPaterno.getText());
            pasar.setString(3, jtxtAMaterno.getText());
            pasar.setString(4, jtxtTotalPagar.getText());
            pasar.setString(5, jcbxNivel.getSelectedItem().toString());
            pasar.setString(6, jcbxCuotaDelMes.getSelectedItem().toString());
            pasar.setString(7, jtxtCorreo.getText()); 
            pasar.setString(8, jTextField1.getText()); 
            pasar.setString(9, codigoEstudiante); 
         
            int filasActualizadas = pasar.executeUpdate();
            if (filasActualizadas > 0) {
                JOptionPane.showMessageDialog(null, "Datos actualizados correctamente.");
                Mostrar(""); // Refresca solo la fila modificada
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el registro con el código de estudiante: " + codigoEstudiante);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VistaPensiones_Balances.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error al actualizar los datos: " + ex.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila para modificar.");
    }
    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        Borrar();
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
int res = JOptionPane.showConfirmDialog(null, "¿Estás seguro que desea salir?");

        if (res == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jcbxCuotaDelMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxCuotaDelMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxCuotaDelMesActionPerformed

    private void jtxtNumeroRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumeroRegistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumeroRegistrosActionPerformed

    private void jtblTablaRegistroDePensionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblTablaRegistroDePensionesMouseClicked
int fila = jtblTablaRegistroDePensiones.rowAtPoint(evt.getPoint());
if (fila >= 0) {
    jTextField5.setText(jtblTablaRegistroDePensiones.getValueAt(fila, 0).toString());
    jtxtCodigo.setText(jtblTablaRegistroDePensiones.getValueAt(fila, 0).toString());
    jtxtNombre.setText(jtblTablaRegistroDePensiones.getValueAt(fila, 1).toString());
    jtxtAPaterno.setText(jtblTablaRegistroDePensiones.getValueAt(fila, 2).toString());
    jtxtAMaterno.setText(jtblTablaRegistroDePensiones.getValueAt(fila, 3).toString());   
    jtxtTotalPagar.setText(jtblTablaRegistroDePensiones.getValueAt(fila, 4).toString());
    jcbxNivel.setSelectedItem(jtblTablaRegistroDePensiones.getValueAt(fila, 5).toString());
    jcbxCuotaDelMes.setSelectedItem(jtblTablaRegistroDePensiones.getValueAt(fila, 6).toString());
    jtxtCorreo.setText(jtblTablaRegistroDePensiones.getValueAt(fila, 8).toString());
    jTextField1.setText(jtblTablaRegistroDePensiones.getValueAt(fila, 9).toString()); 
} else {
    JOptionPane.showMessageDialog(null, "Fila no seleccionada");
 }    }//GEN-LAST:event_jtblTablaRegistroDePensionesMouseClicked

    private void jtxtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCorreoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jbtnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReportesActionPerformed

        pdfBalance();

    }//GEN-LAST:event_jbtnReportesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
pdfRegistro();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtxtBalancedeTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBalancedeTodoActionPerformed

    }//GEN-LAST:event_jtxtBalancedeTodoActionPerformed

    private void jtxtBalancedeTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBalancedeTodoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBalancedeTodoMouseClicked

    private void jtxtTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalPagarActionPerformed

    private void jbtnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPagosActionPerformed
        pagar();
    }//GEN-LAST:event_jbtnPagosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPensiones_Balances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPensiones_Balances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPensiones_Balances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPensiones_Balances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPensiones_Balances().setVisible(true);
            }
        });
    }
public void Mostrar(String estudiante) {
    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("Codigo");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellido Paterno");
    modelo.addColumn("Apellido Materno");
    modelo.addColumn("Pago");
    modelo.addColumn("Nivel");
    modelo.addColumn("Mes");
    modelo.addColumn("Fecha");
    modelo.addColumn("Numero");
    modelo.addColumn("Apoderado");

    jtblTablaRegistroDePensiones.setModel(modelo);

    String sql = "";

    if (estudiante.isEmpty()) {
        sql = "SELECT estudiante, nombres, apellido, materno, pago, nivel, mes, fecha_registro, numero, apoderado FROM apellidopaterno";
    } else {
        sql = "SELECT estudiante, nombres, apellido, materno, pago, nivel, mes, fecha_registro, numero, apoderado FROM apellidopaterno WHERE estudiante LIKE '%" + estudiante + "%'";
    }

    try {
        java.sql.Statement set = conexion.createStatement();
        ResultSet resul = set.executeQuery(sql);

        while (resul.next()) {
            String[] Usuarios = new String[10];
            Usuarios[0] = resul.getString("estudiante");
            Usuarios[1] = resul.getString("nombres");
            Usuarios[2] = resul.getString("apellido");
            Usuarios[3] = resul.getString("materno");
            Usuarios[4] = resul.getString("pago");
            Usuarios[5] = resul.getString("nivel");
            Usuarios[6] = resul.getString("mes");
            Usuarios[7] = resul.getString("fecha_registro");
            Usuarios[8] = resul.getString("numero");
            Usuarios[9] = resul.getString("apoderado"); 
            modelo.addRow(Usuarios);
        }

        jtblTablaRegistroDePensiones.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(VistaPensiones_Balances.class.getName()).log(Level.SEVERE, null, ex);
      
    }
}

public void Guardar() {
  String apellido = jtxtAPaterno.getText();
    String materno = jtxtAMaterno.getText();
    String nombres = jtxtNombre.getText();
    String pago = jtxtTotalPagar.getText();
    String estudiante = jtxtCodigo.getText();
    String nivel = jcbxNivel.getSelectedItem().toString();
    String mes = jcbxCuotaDelMes.getSelectedItem().toString(); 
    String numero = jtxtCorreo.getText(); 
    String apoderado = jTextField1.getText(); 

    if (!apellido.isEmpty()) {
        try {
            String consulta = "INSERT INTO apellidopaterno (apellido, materno, nombres, pago, estudiante, nivel, mes, numero, apoderado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conexion.prepareStatement(consulta);
            pstmt.setString(1, apellido);
            pstmt.setString(2, materno);
            pstmt.setString(3, nombres);
            pstmt.setString(4, pago);
            pstmt.setString(5, estudiante);
            pstmt.setString(6, nivel);
            pstmt.setString(7, mes);
            pstmt.setString(8, numero); 
            pstmt.setString(9, apoderado); 

            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(null, "Datos guardados en la base de datos");

            contarAlumnos();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al guardar los datos en la base de datos: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(null, "El campo de apellido está vacío. No se guardará nada en la base de datos.");
    }
      
}

public void Borrar() {
    int fila = jtblTablaRegistroDePensiones.getSelectedRow();
    if (fila != -1) {
        String estudiante = jtblTablaRegistroDePensiones.getValueAt(fila, 0).toString(); 

        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el registro?", "Eliminar Registro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                
                String sql = "DELETE FROM apellidopaterno WHERE estudiante = ? LIMIT 1"; 
                PreparedStatement borrar = conexion.prepareStatement(sql);
                borrar.setString(1, estudiante);

               
                int filasEliminadas = borrar.executeUpdate();

                if (filasEliminadas > 0) {
                    JOptionPane.showMessageDialog(null, "Registro eliminado correctamente.");
                    Mostrar(""); 
                    contarAlumnos(); 
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontró el registro con el código de estudiante: " + estudiante);
                }
            } catch (SQLException ex) {
                Logger.getLogger(VistaPensiones_Balances.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila para eliminar.");
    }
}

private void contarAlumnos() {
        String sql = "SELECT COUNT(*) AS total FROM apellidopaterno";
        try {
            PreparedStatement pst = conexion.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                int total = rs.getInt("total");
                jtxtNumeroRegistros.setText(String.valueOf(total));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al contar los alumnos: " + e.getMessage());
        }
    }

private void pagar(){
     try {      
            String sql = "SELECT SUM(pago) AS total_pagos FROM apellidopaterno";          
            PreparedStatement stmt = conexion.prepareStatement(sql);     
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {   
                double totalPagos = rs.getDouble("total_pagos");
        
                jtxtBalancedeTodo.setText(String.valueOf(totalPagos));
            }
            rs.close();
            stmt.close();    
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al calcular la suma de pagos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
}
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JButton jbtnPagos;
    private javax.swing.JButton jbtnReportes;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JComboBox<String> jcbxCuotaDelMes;
    private javax.swing.JComboBox<String> jcbxNivel;
    private javax.swing.JTable jtblTablaRegistroDePensiones;
    private javax.swing.JTextField jtxtAMaterno;
    private javax.swing.JTextField jtxtAPaterno;
    private javax.swing.JTextField jtxtBalancedeTodo;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtCorreo;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtNumeroRegistros;
    private javax.swing.JTextField jtxtTotalPagar;
    // End of variables declaration//GEN-END:variables
private void pdfRegistro(){
try{
    FileOutputStream archivo;
    File file = new  File("src/pdf/Registro.pdf");
    archivo=new FileOutputStream(file);
    Document doc = new Document();
    PdfWriter.getInstance(doc, archivo);
    doc.open();
    Image img = Image.getInstance("src/Iconos/pngfind.com-divino-nio-jesus-png-3449909.png");
    
    Paragraph fecha = new Paragraph();
    Font negrita = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD, BaseColor.BLUE);
    fecha.add(Chunk.NEWLINE);
    Date date = new Date();
    fecha.add("Fecha: "+ new SimpleDateFormat("dd-MM-YYY").format(date)+"\n\n");
    
    PdfPTable Encabezado = new PdfPTable(4);
    Encabezado.setWidthPercentage(100);
    Encabezado.getDefaultCell().setBorder(0);
    float[] ColumnaEncabezado = new float[]{20f, 30f, 70f, 40f};
    Encabezado.setWidths(ColumnaEncabezado);
    Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
    
    Encabezado.addCell(img);
    
    String ruc = "20515050851";
    String nom = "Carlos Bonifacio, Ervis Asunción";
    String tel = "(01) 702 – 2051";
    String dir = "Jirón Castrovirreyna";
    String raz = "Divino Niño";
    
    Encabezado.addCell(""); 
    Encabezado.addCell("Ruc: " +ruc+ "\nDirector: " +nom+ "\ntelefono: " +tel+ "\ndireccion: " +dir+ "\nColegio: " +raz);
    Encabezado.addCell(fecha);
    doc.add(Encabezado);
    
    Paragraph stud = new Paragraph();
    stud.add(Chunk.NEWLINE);
    stud.add("Control Registro Pago Pensiones del estudiante:"+"\n\n");
    doc.add(stud);
    
    
    PdfPTable tablastud = new PdfPTable(4);
    tablastud.setWidthPercentage(100);
    tablastud.getDefaultCell().setBorder(0);
    float[] Columnastud = new float[]{10f, 50f, 15f, 20f};
    tablastud.setWidths(Columnastud);
    tablastud.setHorizontalAlignment(Element.ALIGN_LEFT);

    PdfPCell stu1= new PdfPCell(new Phrase("Nombre", negrita));
    PdfPCell stu2= new PdfPCell(new Phrase("Fecha Pago", negrita));
    PdfPCell stu3= new PdfPCell(new Phrase("Mes", negrita));
    PdfPCell stu4= new PdfPCell(new Phrase("Mensualidad", negrita));
    stu1.setBackgroundColor(BaseColor.YELLOW);
    stu2.setBackgroundColor(BaseColor.YELLOW);
    stu3.setBackgroundColor(BaseColor.YELLOW);
    stu4.setBackgroundColor(BaseColor.YELLOW);
    stu1.setBorder(0);
    stu2.setBorder(0);
    stu3.setBorder(0);
    stu4.setBorder(0);
    tablastud.addCell(stu1);
    tablastud.addCell(stu2);
    tablastud.addCell(stu3);
    tablastud.addCell(stu4);
    for (int i = 0; i < jtblTablaRegistroDePensiones.getRowCount(); i++){
    String Nombre = jtblTablaRegistroDePensiones.getValueAt(i, 1).toString();
    String FechaPago = jtblTablaRegistroDePensiones.getValueAt(i, 7).toString();
    String mes = jtblTablaRegistroDePensiones.getValueAt(i, 6).toString();
    String mensualidad = jtblTablaRegistroDePensiones.getValueAt(i, 4).toString();
    
    tablastud.addCell(Nombre);
    tablastud.addCell(FechaPago);
    tablastud.addCell(mes);
    tablastud.addCell(mensualidad);
}
   
    doc.add(tablastud);
    Paragraph firma = new Paragraph();
    firma.add(Chunk.NEWLINE);
    firma.add("Cancelación y Firma\n");
    firma.add("----------------------");
    firma.setAlignment(Element.ALIGN_CENTER);
    doc.add(firma);
    
    doc.close();
    archivo.close();
    Desktop.getDesktop().open(file);
}catch (DocumentException | IOException e) {
    System.out.println(e.toString());
}
}
private void pdfBalance(){
try{
    FileOutputStream archivo;
    File file = new  File("src/pdf/Balance.pdf");
    archivo=new FileOutputStream(file);
    Document doc = new Document();
    PdfWriter.getInstance(doc, archivo);
    doc.open();
    Image img = Image.getInstance("src/Iconos/pngfind.com-divino-nio-jesus-png-3449909.png");
    
    Paragraph fecha = new Paragraph();
    Font negrita = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD, BaseColor.BLUE);
    fecha.add(Chunk.NEWLINE);
    Date date = new Date();
    fecha.add("Fecha: "+ new SimpleDateFormat("dd-MM-YYYY").format(date)+"\n\n");
    
    PdfPTable Encabezado = new PdfPTable(4);
    Encabezado.setWidthPercentage(100);
    Encabezado.getDefaultCell().setBorder(0);
    float[] ColumnaEncabezado = new float[]{20f, 30f, 70f, 40f};
    Encabezado.setWidths(ColumnaEncabezado);
    Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
    
    Encabezado.addCell(img);
    
    String ruc = "20515050851";
    String nom = "Carlos Bonifacio, Ervis Asunción";
    String tel = "(01) 702 – 2051";
    String dir = "Jirón Castrovirreyna";
    String raz = "Divino Niño";
    
    Encabezado.addCell(""); 
    Encabezado.addCell("Ruc: " +ruc+ "\nDirector: " +nom+ "\ntelefono: " +tel+ "\ndireccion: " +dir+ "\nColegio: " +raz);
    Encabezado.addCell(fecha);
    doc.add(Encabezado);
    
    Paragraph stud = new Paragraph();
    stud.add(Chunk.NEWLINE);
    stud.add("Reporte Balance del estudiante::"+"\n\n");
    doc.add(stud);
    
    
    PdfPTable tablastud = new PdfPTable(4);
    tablastud.setWidthPercentage(100);
    tablastud.getDefaultCell().setBorder(0);
    float[] Columnastud = new float[]{10f, 50f, 15f, 20f};
    tablastud.setWidths(Columnastud);
    tablastud.setHorizontalAlignment(Element.ALIGN_LEFT);

    PdfPCell stu1= new PdfPCell(new Phrase("Nombre", negrita));
    PdfPCell stu2= new PdfPCell(new Phrase("Celular", negrita));
    PdfPCell stu3= new PdfPCell(new Phrase("Meses", negrita));
    PdfPCell stu4= new PdfPCell(new Phrase("Mensualidad", negrita));
    stu1.setBackgroundColor(BaseColor.YELLOW);
    stu2.setBackgroundColor(BaseColor.YELLOW);
    stu3.setBackgroundColor(BaseColor.YELLOW);
    stu4.setBackgroundColor(BaseColor.YELLOW);
    stu1.setBorder(0);
    stu2.setBorder(0);
    stu3.setBorder(0);
    stu4.setBorder(0);
    tablastud.addCell(stu1);
    tablastud.addCell(stu2);
    tablastud.addCell(stu3);
    tablastud.addCell(stu4);
    for (int i = 0; i < jtblTablaRegistroDePensiones.getRowCount(); i++){
    String Nombre = jtblTablaRegistroDePensiones.getValueAt(i, 1).toString();
    String Celular = jtblTablaRegistroDePensiones.getValueAt(i, 8).toString();
    String Meses = jtblTablaRegistroDePensiones.getValueAt(i, 6).toString();
    String mensualidad = jtblTablaRegistroDePensiones.getValueAt(i, 4).toString();
    
    tablastud.addCell(Nombre);
    tablastud.addCell(Celular);
    tablastud.addCell(Meses);
    tablastud.addCell(mensualidad);
}
   
    doc.add(tablastud);
    
    Paragraph info = new Paragraph();
    info.add(Chunk.NEWLINE);
     try {      
            String sql = "SELECT SUM(pago) AS total_pagos FROM apellidopaterno";          
            PreparedStatement stmt = conexion.prepareStatement(sql);     
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {   
                double totalPagos = rs.getDouble("total_pagos");
        
                jtxtBalancedeTodo.setText(String.valueOf(totalPagos));
                 info.add("Total a Pagar "+ totalPagos);
    info.setAlignment(Element.ALIGN_RIGHT);
    doc.add(info);
    
            }
            rs.close();
            stmt.close();    
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al calcular la suma de pagos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
   
    Paragraph firma = new Paragraph();
    firma.add(Chunk.NEWLINE);
    firma.add("Cancelación y Firma\n");
    firma.add("----------------------");
    firma.setAlignment(Element.ALIGN_CENTER);
    doc.add(firma);
    
    doc.close();
    archivo.close();
    Desktop.getDesktop().open(file);
    
}catch (DocumentException | IOException e) {
    System.out.println(e.toString());
}
}
}
